dist: trusty
sudo: required
language: node_js
node_js:
- '6.1'
os:
- linux
before_script:
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- npm run test-once
branches:
  only:
  - master
  - develop
deploy:
  provider: $PROVIDER
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  revision_type: $REVISION_TYPE
  application: $APPLICATION
  deployment_group: $DEPLOYMENT_GROUP
  on:
    all_branches: true
    repo: $REPO
secret_access_key:
  secure: $SECURE
after_deploy:
- "/home/angular/after_deploy_1.sh"
- "./after_deploy_2.sh"
