version: 0.0
os: linux
files:
  - source: /
    destination: /home/angular/webapps/www/
hooks:
  BeforeInstall:
    - location: deploy/start_server
      timeout: 60
      runas: root
  ApplicationStop:
    - location: deploy/stop_server
      timeout: 60
      runas: angular